version: '2'
services:
  kibana:
    image: kibana:6.2.4
    depends_on:
      - elasticsearch
    environment:
      SERVER_NAME: kibana
      SERVER_HOST: kibana
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ES_JAVA_OPTS: -Xms512m -Xmx512m
    ports:
      - "5601:5601"
  elasticsearch:
    image: elasticsearch:6.2.4
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USER: ${USER}
        UID: ${UID}
    image: cyberlolz
    command: ./setup
    volumes:
      - ".:/cyberlolz"
    depends_on:
      - db
      - kibana
    ports:
      - "3001:3000"
    env_file: .env
  db:
    image: mysql:5.7
    restart: unless-stopped
    env_file: .env
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
