#!/bin/bash

bundle exec rake cyberlolz_setup:_index
bundle exec rake cyberlolz_setup:_pattern
bundle exec rake cyberlolz_setup:_advanced_setting
rm -f tmp/pids/server.pid
bundle exec rake db:setup
bundle exec rails s -b 0.0.0.0
